// <auto-generated />
namespace Typor.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Products_are_virtual_in_Order_and_ShoppingCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products_are_virtual_in_Order_and_ShoppingCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201506231155380_Products_are_virtual_in_Order_and_ShoppingCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
